@url = http://localhost:3000
### Listado de rectangulos
GET {{url}}/rectangulos


### Detalles de rectangulos
GET {{url}}/rectangulos/2

### Crear rectangulo
POST {{url}}/rectangulos
Content-Type: application/json

{
    "altura": 5.5,
    "base": 10.5
}

### Modificar rectangulo
PUT {{url}}/rectangulos/2
Content-Type: application/json

{
    "altura": 7,
    "base": 8.8
    
}
### Quitar rectangulo
DELETE {{url}}/rectangulos/4
